provider:
  win: github_actions
  linux_64: github_actions
  linux_aarch64: travis
  osx_64: github_actions
  osx_arm64: travis
build_platform:
  osx_arm64: osx_arm64
  linux_aarch64: linux_aarch64
test: native_and_emulated
